# config.yml
# SwiftFoundationHelpers
#
# Copyright © 2026 Dagitali LLC. All rights reserved.

---

blank_issues_enabled: false
contact_links:
  - name: 💬 General Question
    url: https://github.com/Dagitali/SwiftFoundationHelpers/discussions/
    about: Please ask and answer questions as a discussion thread.
