# generate-swift-package-api-docs.yml
# SwiftFoundationHelpers
#
# Copyright © 2024 Dagitali LLC. All rights reserved.
#
# A GitHub Actions workflow file that automates generating API documentation for
# the Swift package.
#
# See:
# 1. https://danielsaidi.com/blog/2024/03/10/automatically-publish-docc-to-
#    github-pages-with-github-actions
# 2. https://github.com/actions
# 3. https://github.com/features/actions
# 4. https://docs.github.com/en/actions

---

name: Generate Swift package API docs

on:
  push:               # Allow automatic triggering for pushes.
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering.

# Grant GITHUB_TOKEN permission to deploy to GitHub Pages.
permissions:
  contents: read
  pages: write     # To deploy to GitHub Pages.
  id-token: write  # To verify an appropriate deployment source.

# Allow one concurrent deployment.
concurrency:
  group: "pages"
  cancel-in-progress: true

# Build and deploy the DocC documentation.
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployments.outputs.pages_url }}
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up GitHub Pages
      uses: actions/configure-pages@v5
    - name: Set up Swift
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - name: Build DocC archive
      run: |
        swift package resolve
        xcodebuild docbuild \
          -scheme SwiftFoundationHelpers \
          -derivedDataPath /tmp/docbuild \
          -destination 'generic/platform=iOS'
    - name: Convert DocC archive to static website
      run: |
        $(xcrun --find docc) convert \
            /tmp/docbuild/Build/Products/Debug-iphoneos/SwiftFoundationHelpers.doccarchive \
            --output-path docs \
            --hosting-base-path 'SwiftFoundationHelpers' \
            --transform-for-static-hosting \
            --allow-arbitrary-catalog-directories
        echo "<script>window.location.href += \"/documentation/swiftfoundationhelpers\"</script>" > docs/index.html
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: 'docs'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
