# qa-swift-package.yml
# SwiftFoundationHelpers
#
# Copyright © 2024 Dagitali LLC. All rights reserved.
#
# A GitHub Actions workflow file that automates quality assuring a Swift
# package.
#
# See:
# 1. https://github.com/actions
# 2. https://github.com/features/actions
# 3. https://github.com/marketplace/actions/setup-swift
# 4. https://docs.github.com/en/actions
# 5. https://docs.github.com/en/actions/use-cases-and-examples/
#    building-and-testing/building-and-testing-swift

---

name: QA swift package

on:
  pull_request:       # Allow automatic triggering for PRs.
    branches:
      - bugfix/**
      - feature/**
    types:
      - opened
      - closed
      - labeled
  push:               # Allow automatic triggering for pushes.
    branches:
      - develop
      - main
      - versions
  workflow_dispatch:  # Allow manual triggering.

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Swift environment
        run: |
          sudo apt-get update
          sudo apt-get install -y swift
      - name: Set up Python environment
        run: |
          python3 -m venv ~/.venv
          source ~/.venv/bin/activate
      - name: Install Pre-Commit
        run: |
          pip install pre-commit
      - name: Run Pre-Commit hooks
        run: |
          pre-commit run --all-files
  test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }} (${{ matrix.destination }})
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 14 Pro"
        os:
          - ubuntu-latest
          - macos-15
        swift:
          # - '6.0.2'
          # - '6.0.1'
          - '6.0'
          # - '5.10.1'
          # - '5.10.0'
          # - '5.9.2'
          # - '5.9.2'
          # - '5.9.1'
          # - '5.9'
          # - '5.8.1'
          # - '5.8'
          # - '5.7.3'
          # - '5.7.2'
          # - '5.7.1'
          # - '5.7'
          # - '5.5'
          # - '5.4'
          # - '5.3'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Swift version
        run: |
          swift --version
      - name: Build Swift package
        run: |
          swift build -v
      - name: Run tests on Swift package (Swift CLI)
        run: |
          swift test -v
      # - name: Run tests on Swift package (Xcode)
      #   run: xcodebuild test -workspace SwiftFoundationHelpers.xcworkspace -scheme SwiftFoundationHelpers clean build -sdk iphoneos -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14 Pro Max" CODE_SIGNING_ALLOWED=No
      # - name: Generate code coverage report
